CREATE TABLE `SHIPWRECK` (
	`ID` INT(11) NOT NULL AUTO_INCREMENT,
	`NAME` VARCHAR(255) NOT NULL DEFAULT '0',
	`DESCRIPTION` VARCHAR(2000) NOT NULL DEFAULT '0',
	`CONDITION` VARCHAR(255) NOT NULL DEFAULT '0',
	`DEPTH` INT(11) NOT NULL DEFAULT '0',
	`LATITUDE` DOUBLE NOT NULL DEFAULT '0',
	`LONGITUDE` DOUBLE NOT NULL DEFAULT '0',
	`YEAR_DISCOVERED` INT(11) NOT NULL DEFAULT '0',
	INDEX `ID` (`ID`)
)
ENGINE=InnoDB
;
